// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNxbfQgUAI8lo1_zz6t_GDXX-7J24bjo',
    appId: '1:211047451340:web:51ad5795de2b3708851069',
    messagingSenderId: '211047451340',
    projectId: 'students-29674',
    authDomain: 'students-29674.firebaseapp.com',
    storageBucket: 'students-29674.appspot.com',
    measurementId: 'G-MMNVG1PEKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdE38Qz3XGH03P_B6zRIk0otSQzSvGmdw',
    appId: '1:211047451340:android:3f72f8b0e4ae0b90851069',
    messagingSenderId: '211047451340',
    projectId: 'students-29674',
    storageBucket: 'students-29674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxANqYvojsP0rzzq4tE9ApU-i_mZvZx2M',
    appId: '1:211047451340:ios:50f510bb4b9bec23851069',
    messagingSenderId: '211047451340',
    projectId: 'students-29674',
    storageBucket: 'students-29674.appspot.com',
    iosClientId: '211047451340-l42a585as3bdme2jfpnvlkv5rebdrv23.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxANqYvojsP0rzzq4tE9ApU-i_mZvZx2M',
    appId: '1:211047451340:ios:50f510bb4b9bec23851069',
    messagingSenderId: '211047451340',
    projectId: 'students-29674',
    storageBucket: 'students-29674.appspot.com',
    iosClientId: '211047451340-l42a585as3bdme2jfpnvlkv5rebdrv23.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );
}
